### ISSUE TITLE
data preparation for eqtls

### ISSUE THREAD

**Issue by stephens999** [stephens999/gtex-viz#1]
we need a script that takes a bunch of Sarah's eQTL results (posterior means), and creates a data frame
with the form
gene snp tissue1name tissue2name.... 
apoe rs1  posteriormeantissue1 posteriormeantissue2 ...

The script can be included here in the repo, but we'll keep the data files out of the repo for now.
(so keep them on midway?)

**Comment by stephens999** [comment]
Key detail: this file should contain just one "top" eqtl per gene. Eg the one with the largest posterior mean effect size. This is because eQTLs in the same gene are often highly correlated, so dominate the similarity plots etc and are essentially redundant.

**Comment by surbut** [comment]
The gene snp names and tissue names are 
in the analysis/june2014/types_v1/et_shrunken_batch1_withbma/ directory under 'et_genesnpnames"

**Comment by surbut** [comment]
script for adding tissue names and gene snp names to rows is in /home/surbut/analysis/june2014/types_v1/et_shrunken_batch1_withbma/genesnpnamesscript.R

**Comment by surbut** [comment]
you didn't specify you you wanted the 'top' eQTL per gene chosen - I'm using the framework to choose the snp with the maximum absolute posterior mean for the gene

**Comment by stephens999** [comment]
can you apply the script to create a data file of this type, and indicate where that data file lives in the README in the data subdirectory?
