### ISSUE TITLE
Data subdirectory needs tidying to only include dats

### ISSUE THREAD

**Issue by stephens999** [stephens999/gtex-viz#10]
Can you move rmd files for plotting to another subdirectory? Maybe plots?  You may want subdirectories of plots to organize  different types of plot.
 Can you also use relative paths instead of absolute paths,  and avoid setwd. Rmd files should always be run from the directory they live in.  Thanks!

**Comment by stephens999** [comment]
this is much better thanks! We should think about whether we want a data subdirectory and a results subdirectory, but not before Monday because don't want to break anything before then.. I'll close this for now

**Comment by surbut** [comment]
my pleasure - and  i was thinking the same thing about the subdirectory delay. I’m working on the lfsr correlation plots right now … matrix-ash simulations were too enticing to stay away from this morning:)
