### ISSUE TITLE
expression: patterns of expression across genes

### ISSUE THREAD

**Issue by kkdey** [stephens999/gtex-viz#12]
To perform t-SNE on the gene expression (possibly normalized log read counts) to see if similarly behaving genes cluster together. For instance, if the genes which are highly expressed in brain and not much in other tissues cluster together. One way to figure that out would be 
1. Perform SFA on the genes and try to see if any of the factors are tissue specific
2. Perform t-SNE on the gene expression or normalized gene expression to see if there are any visible patterns.
3. Perform t-SNE on the gene expression post the SFA analysis to see if there are any visible patterns

**Comment by kkdey** [comment]
t-SNE on the gene expression : https://github.com/stephens999/gtex-viz/blob/master/gtex.Kushal/plots/gene_tSNE.html

**Comment by kkdey** [comment]
I have the matrix of proportion values now on Github: https://github.com/stephens999/gtex-viz/blob/master/gtex.Kushal/data/prop_sig_matrix_0_3.txt 

You can just read it and form the heatmap and it should show same patterns as in cor_thresh_0_3

**Comment by stephens999** [comment]
Thx @kkdey , but I think you added this under the wrong issue

**Comment by kkdey** [comment]
Ohh sorry...I wanted to put it under "Patterns of expression across tissues"...I will move it there...thanks for pointing out...
