### ISSUE TITLE
data files need gene names

### ISSUE THREAD

**Issue by stephens999** [stephens999/gtex-viz#13]
@kkdey can you add the gene names (Ensembl ids) to the rows
of the expression counts file, so that we know which row corresponds to which gene?

@kkdey @surbut in general we have  a problem with names being in different
files from the actual data. It is asking for mistakes ultimately. In the future we
should have a rule to include meta-data (like tissue names, gene-snp names etc) in the same files
as the numbers. So that, for example, the column names and row names of a dataframe
are kept together with the dataframe.

**Comment by surbut** [comment]
HI Matthew, 

The rownames of the lfsr, postmeans and marginal var all have the gene snp names in the files. The gene-snp names are also in the original data file in the t score and se beta hat files (in column 2).

cd gtex-viz/data/ET_model_stronggenesnps
cat post.mean.et_withbma.txt | head 
"ENSG00000048707.9_rs1148458" -0.249106299314983 -0.159850348404364 -0.555370735300058 -0.263946722185617 -0.131467516019511 -0.11010491191122 -0.794426968091724 -0.902453004147123 -0.895786822089615 -1.05284903987585 -0.930608708564712 -0.853909030476391 -0.683692433511795 -0.655347863639577 -0.894878005337084 -0.776350223663671 -0.208620121921689 -0.558750396653094 -0.549031603363606 -0.335415387746847 -0.464317099966014 -0.325325688469794 -0.454836297317932 -0.391821538524435 -0.329572901165271 -0.282817678581454 -0.367003307204012 -0.452137261182468 -0.189124440344878 -0.388193640159576 -0.0417447914494847 -0.445115024489682 -0.93715987296227 -0.453530026727483 -0.0356209695171497 -0.0463076976546073 -0.278918301603872 -0.491833834897297 -0.401913371169579 -2.37211537110267 -0.727309124027008 -0.0318965860634937 -0.147999065772296 -0.369800349860231

for example. The column names are the tissues.

Best,
Sarah

**Comment by surbut** [comment]
and i’m still working on that interactive bar plot. I don’t give up that easy:)

**Comment by surbut** [comment]
Got the interactive barplot using plotly. Here’s the link to the plot I made. So cool and easy. I’ll put the rscript up but you need to actually run it (not knit) to get the url.

https://plot.ly/~DemoAccount/866 https://plot.ly/~DemoAccount/866

**Comment by kkdey** [comment]
Added the Ensembl gene IDs to the cis gene expression ("without the part after the ".", as it tends to get confusing when searching for gene names in BioMArt)....The updated file is in : https://github.com/stephens999/gtex-viz/blob/master/gtex.Kushal/data/cis_gene_expression_per_tissue.txt

**Comment by stephens999** [comment]
Thx
