### ISSUE TITLE
Rscripts need documentation

### ISSUE THREAD

**Issue by stephens999** [stephens999/gtex-viz#9]
can you add a header to the top of your Rscript indicating how it should be used?

**Comment by surbut** [comment]
Sorry I'm stuffed in the backseat on the way to family bike ride in traverse  city so I don't think I can reply to the GitHub request - but the Rscript is meant to be run interactively in the directory listed at the top of the file, or you can just write a quick bash wrapper to sbatch it but it only takes a minute. 

It correctly names all the rows and columns - I've been using it for all my plots of posterior means by gene SNP name.

**Comment by stephens999** [comment]
Sure,  just add the info when you get the chance.

Matthew

**Comment by surbut** [comment]
I did label and create the : strongmeans_first_batch.txt in the types_v1 with one SNP per Gene and and tissue names in the column name if you need it. 

 Kushal very nicely put it in the et_with_bma directory also. I'll just add the readme on Monday. thanks.
